# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03185eb31a524711d6e03d3b853c335aec6ff55e2bc5d22fbcdb878ef7721e7891485ffaae60d3084b2e0c1d29046a200ecaea437a0d69d01fb96676a603b6da

test:
  secret_key_base: 538331bfa2b1e7f7cfe6cb8749892687a539f18f8c5b95ad5d989f71d77024ead5cd5136231d03aac6c4b849bca177676d46d4f087fe84da1541ba8eb6a4faa9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
